//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLap.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebLap.Resources.ResourceWeb", typeof(ResourceWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories Page.
        /// </summary>
        public static string CategoriesPage {
            get {
                return ResourceManager.GetString("CategoriesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Name.
        /// </summary>
        public static string ColorName {
            get {
                return ResourceManager.GetString("ColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors Page.
        /// </summary>
        public static string ColorsPage {
            get {
                return ResourceManager.GetString("ColorsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactNumber.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create account.
        /// </summary>
        public static string create_account {
            get {
                return ResourceManager.GetString("create_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string CreateCategory {
            get {
                return ResourceManager.GetString("CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Color.
        /// </summary>
        public static string CreateColor {
            get {
                return ResourceManager.GetString("CreateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Operating System.
        /// </summary>
        public static string CreateOs {
            get {
                return ResourceManager.GetString("CreateOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Page.
        /// </summary>
        public static string CreatePagePage {
            get {
                return ResourceManager.GetString("CreatePagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product Page.
        /// </summary>
        public static string CreateProductPage {
            get {
                return ResourceManager.GetString("CreateProductPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Slider Page.
        /// </summary>
        public static string CreateSliderPage {
            get {
                return ResourceManager.GetString("CreateSliderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Type.
        /// </summary>
        public static string CreateType {
            get {
                return ResourceManager.GetString("CreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Setting Page.
        /// </summary>
        public static string EditSettingPage {
            get {
                return ResourceManager.GetString("EditSettingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Fname {
            get {
                return ResourceManager.GetString("Fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HardDisk.
        /// </summary>
        public static string HardDisk {
            get {
                return ResourceManager.GetString("HardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Img {
            get {
                return ResourceManager.GetString("Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instgram Link.
        /// </summary>
        public static string InstgramLink {
            get {
                return ResourceManager.GetString("InstgramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Lname {
            get {
                return ResourceManager.GetString("Lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System Name.
        /// </summary>
        public static string OsName {
            get {
                return ResourceManager.GetString("OsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System Page.
        /// </summary>
        public static string OsPage {
            get {
                return ResourceManager.GetString("OsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Pages.
        /// </summary>
        public static string PagePages {
            get {
                return ResourceManager.GetString("PagePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Page.
        /// </summary>
        public static string ProductsPage {
            get {
                return ResourceManager.GetString("ProductsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RamSize.
        /// </summary>
        public static string RamSize {
            get {
                return ResourceManager.GetString("RamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesPage.
        /// </summary>
        public static string RolesPage {
            get {
                return ResourceManager.GetString("RolesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Reselution.
        /// </summary>
        public static string ScreenReselution {
            get {
                return ResourceManager.GetString("ScreenReselution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Page.
        /// </summary>
        public static string SettingPage {
            get {
                return ResourceManager.GetString("SettingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Name.
        /// </summary>
        public static string SliderName {
            get {
                return ResourceManager.GetString("SliderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders Page.
        /// </summary>
        public static string SliderPage {
            get {
                return ResourceManager.GetString("SliderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tittle.
        /// </summary>
        public static string Tittle {
            get {
                return ResourceManager.GetString("Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Link.
        /// </summary>
        public static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Page.
        /// </summary>
        public static string TypePage {
            get {
                return ResourceManager.GetString("TypePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Description.
        /// </summary>
        public static string WebsiteDesc {
            get {
                return ResourceManager.GetString("WebsiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Name.
        /// </summary>
        public static string WebsiteName {
            get {
                return ResourceManager.GetString("WebsiteName", resourceCulture);
            }
        }
    }
}
