//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domin.Resources.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address required.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryName required.
        /// </summary>
        public static string CayegoryName2 {
            get {
                return ResourceManager.GetString("CayegoryName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorName required.
        /// </summary>
        public static string ColorName {
            get {
                return ResourceManager.GetString("ColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number required.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Page required.
        /// </summary>
        public static string DescPage {
            get {
                return ResourceManager.GetString("DescPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email required.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Not Exist.
        /// </summary>
        public static string EmailNotExist {
            get {
                return ResourceManager.GetString("EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fname required.
        /// </summary>
        public static string Fname {
            get {
                return ResourceManager.GetString("Fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HardDisk required.
        /// </summary>
        public static string HardDisk {
            get {
                return ResourceManager.GetString("HardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Img Page required.
        /// </summary>
        public static string ImgPage {
            get {
                return ResourceManager.GetString("ImgPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstgramLink required.
        /// </summary>
        public static string InstgramLink {
            get {
                return ResourceManager.GetString("InstgramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lname required.
        /// </summary>
        public static string Lname {
            get {
                return ResourceManager.GetString("Lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Img required.
        /// </summary>
        public static string LogoImg {
            get {
                return ResourceManager.GetString("LogoImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word must be twenty characters max.
        /// </summary>
        public static string MaxWord {
            get {
                return ResourceManager.GetString("MaxWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word must be at least two characters.
        /// </summary>
        public static string MinWord {
            get {
                return ResourceManager.GetString("MinWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OsName required.
        /// </summary>
        public static string OsName {
            get {
                return ResourceManager.GetString("OsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageImg required.
        /// </summary>
        public static string PageImg {
            get {
                return ResourceManager.GetString("PageImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password should be 6 charcter at least.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductImg required.
        /// </summary>
        public static string ProductImg {
            get {
                return ResourceManager.GetString("ProductImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductName required.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductPrice required.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RamSize required.
        /// </summary>
        public static string RamSize {
            get {
                return ResourceManager.GetString("RamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleName Required.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Reselution required.
        /// </summary>
        public static string ScreenReselution {
            get {
                return ResourceManager.GetString("ScreenReselution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Img required.
        /// </summary>
        public static string SliderImg {
            get {
                return ResourceManager.GetString("SliderImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SliderName required.
        /// </summary>
        public static string SliderName {
            get {
                return ResourceManager.GetString("SliderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TittlePage required.
        /// </summary>
        public static string TittlePage {
            get {
                return ResourceManager.GetString("TittlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterLink required.
        /// </summary>
        public static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeName required.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter valid email.
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number must be exactly 10 digits.
        /// </summary>
        public static string ValidNumber {
            get {
                return ResourceManager.GetString("ValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebsiteDescription required.
        /// </summary>
        public static string WebsiteDescription {
            get {
                return ResourceManager.GetString("WebsiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebsiteName required.
        /// </summary>
        public static string WebsiteName {
            get {
                return ResourceManager.GetString("WebsiteName", resourceCulture);
            }
        }
    }
}
